### PR TITLE
Change (breaking!): Rename import to `airbyte_api` to make `airbyte-api` compatible with PyAirbyte

### LINKED ISSUE #67: Resolve compatibility conflicts with PyAirbyte (rename library and rebuild)
Currently, this package (`airbyte-api`) imports with `import airbyte`. The new PyAirbyte library _also_ imports with `import airbyte`. 

I'm starting to work through this issue, trialing a few approaches in

- #66 

Options I'm aware of:

1. Rename the package to something like `airbyte_api` or `airbyte_cdk`.
1. Create a namespaces package, where `airbyte-api` imports as `airbyte.sdk`, which would be grafted into the same top-level `airbyte` namespace as PyAirbyte, but withought the two packages conflicting.

### PR DESCRIPTION
**Pull request by aaronsteers**
Resolves #67

### CODE REVIEW

**Comment by aaronsteers** [comment]
I don't know how to run codegen, so I've created a new branch with manual rename/move.

`aj/manual_rename_dir`

**Comment by simplesagar** [comment]
If you merge this and then go to `Actions tab` --> `Pick the workflow "Generate"` --> `Run Workflow (click the 'force generate' option since the spec has not changed`

**Comment by aaronsteers** [comment]
Thanks, @simplesagar ! Who else do you think we should add as approver here?

Cc @bgroff

**Comment by aaronsteers** [comment]
@airbytehq/platform-enablement - This will be a breaking change. Flagging for visibility + feedback.

**Pull request merged**
